# This file was generated by GoReleaser. DO NOT EDIT.
cask "hbactl" do
  name "hbactl"
  desc "CLI to manage PostgreSQL pg_hba.conf safely"
  homepage "https://github.com/hrodrig/hbactl"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hbactl"

  on_macos do
    on_intel do
      url "https://github.com/hrodrig/hbactl/releases/download/v#{version}/hbactl_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/hbactl/"
      sha256 "232d77b628b8b53fa979b894104e4cadfd35aa5f8c234e378eef5c79f4903d1d"
    end
    on_arm do
      url "https://github.com/hrodrig/hbactl/releases/download/v#{version}/hbactl_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/hbactl/"
      sha256 "d6f39d75eef373a02ca8d6c72df640025d292174e79640473a6598982d382546"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hrodrig/hbactl/releases/download/v#{version}/hbactl_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/hbactl/"
      sha256 "6767e0cf16612452828270c148a5b1383cc5d4ef8de3da420807b95f89143997"
    end
    on_arm do
      url "https://github.com/hrodrig/hbactl/releases/download/v#{version}/hbactl_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/hbactl/"
      sha256 "6d3a453648ac2bcaf9f3f1420a0f513258f5ecaa09cb57cafdd26ef9825f15d5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hbactl"]
    end
  end

  # No zap stanza required
end
