# This file was generated by GoReleaser. DO NOT EDIT.
cask "hbactl" do
  name "hbactl"
  desc "CLI to manage PostgreSQL pg_hba.conf safely"
  homepage "https://github.com/hrodrig/hbactl"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hbactl"

  on_macos do
    on_intel do
      url "https://github.com/hrodrig/hbactl/releases/download/v#{version}/hbactl_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/hbactl/"
      sha256 "f7329597b3880ac11c599a679d94fc45bb8e94c8fdfe1a7a8d6ab04e1534975f"
    end
    on_arm do
      url "https://github.com/hrodrig/hbactl/releases/download/v#{version}/hbactl_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/hbactl/"
      sha256 "c0b83cbf0721526e039d015ed5ee6cafd7ee571c6208ae6d991fd4d4eaa3eca0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hrodrig/hbactl/releases/download/v#{version}/hbactl_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/hbactl/"
      sha256 "5160014a02aff9b3841dd70abde168ebbf53e816a2fd1b94b05951024a0b0131"
    end
    on_arm do
      url "https://github.com/hrodrig/hbactl/releases/download/v#{version}/hbactl_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/hbactl/"
      sha256 "c69f8e513f151883d67dfe384d0c5d6f683f422d39977c5589003a942bbfb32f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hbactl"]
    end
  end

  # No zap stanza required
end
